version: '3.7'

services:
  jobmanager:
    image: flink:1.19.0-scala_2.12-java8
    ports:
      - "8081:8081"
    command: jobmanager
    environment:
      - FLINK_PROPERTIES
    networks:
      - flink-network

  taskmanager:
    image: flink:1.19.0-scala_2.12-java8
    depends_on:
      - jobmanager
    command: taskmanager
    environment:
      - FLINK_PROPERTIES
    networks:
      - flink-network

networks:
  flink-network:
    driver: bridge