version: '3.8'

services:
  spark-master:
    container_name: spark-master
    build:
      context: .
      target: pyspark
    image: spark-image
    entrypoint: [ './entrypoint.sh', 'master' ]
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080" ]
      interval: 5s
      timeout: 3s
      retries: 3
    volumes:
      - ./data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
      - ./notebooks:/opt/notebooks
    env_file:
      - .env.spark
    ports:
      - '9090:8080'
      - '7077:7077'


  spark-history-server:
    container_name: spark-history
    image: spark-image
    entrypoint: ['./entrypoint.sh', 'history']
    depends_on:
      - spark-master
    env_file:
      - .env.spark
    volumes:
      - spark-logs:/opt/spark/spark-events
    ports:
      - '18080:18080'

  

  spark-worker-1:
    image: spark-image
    container_name: spark-worker-1
    entrypoint: ["./entrypoint.sh", "worker", "8081"]
    depends_on:
      - spark-master
    environment:
      - SPARK_PUBLIC_DNS=localhost
    env_file:
      - .env.spark
    volumes:
      - ./data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
    ports:
      - "8081:8081"

  spark-worker-2:
    image: spark-image
    container_name: spark-worker-2
    entrypoint: ["./entrypoint.sh", "worker", "8082"]
    depends_on:
      - spark-master
    environment:
      - SPARK_PUBLIC_DNS=localhost
    env_file:
      - .env.spark
    volumes:
      - ./data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
    ports:
      - "8082:8082"

  spark-worker-3:
    image: spark-image
    container_name: spark-worker-3
    entrypoint: ["./entrypoint.sh", "worker", "8083"]
    depends_on:
      - spark-master
    environment:
      - SPARK_PUBLIC_DNS=localhost
    env_file:
      - .env.spark
    volumes:
      - ./data:/opt/spark/data
      - ./spark_apps:/opt/spark/apps
      - spark-logs:/opt/spark/spark-events
    ports:
      - "8083:8083"

volumes:
  spark-logs:
