name: Pre-Commit

on:
  push:
    branches:
      - master

jobs:
  pre_commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install pre-commit
        run: |
          python -m pip install --upgrade pip
          pip install pre-commit

      - name: Get Modified Files
        id: modified_files
        run: |
          echo "::set-output name=files::$(git diff --name-only HEAD^ HEAD | xargs)"
      
      - name: Run pre-commit on modified files
        run: |
          pre-commit run --files ${{ steps.modified_files.outputs.files }}
